{{- if .Values.secrets.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "application.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "application.fullname" . }}-{{ .Release.Revision }}
    type: Opaque
    data: 
    {{- range .Values.secrets.objects }}
    - objectName: {{ .secret }}
      key: {{ .secret }}
    {{- end}}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"         
    userAssignedIdentityID: {{ .Values.secrets.clientId }}
    keyvaultName: {{ .Values.secrets.keyvaultname }}        
    tenantId: {{ .Values.secrets.tenantId }}    
    objects:  |
      array:
        {{- range .Values.secrets.objects }}
        - |
          objectName: {{ .secret }}
          objectType: secret              
        {{- end}}
{{- end }}
